dataset:
  data_path: data/creditcard.csv
  input_features: 23
  model_dir: models/creditcard
  model_path: models/original/sigmoid/creditcard
  name: creditcard
  num_classes: 2
  path: models/original/sigmoid/creditcard
  target_column: Y
export:
  edge_impulse:
    enabled: false
    project_id: 669207
  enabled: false
  onnx_dir: models/creditcard/relu/onnx
  save_dir: models/pruned/sigmoid/creditcard
inference:
  batch_size: 32
  enabled: true
  output_dir: results/inference/sigmoid/creditcard
model:
  activation: sigmoid
  base_dir: models/creditcard/relu
  hidden_neurons: 46
  input_features: 23
  model_save_path: models/creditcard
output:
  results_dir: results/creditcard
  save_dir: models/pruned/sigmoid/creditcard
pruning:
  accuracy_drop: 0.05
  activity_threshold: 0.1
  correlation_threshold: 0.8
  enabled: true
  pruned: false
  save_dir: models/pruned/sigmoid/creditcard
  sensitivity_threshold: 0.01
  validation:
    accuracy_weight: 1.0
    batch_size: 3
    max_accuracy_drop: 0.05
    max_neurons_pruned: 8
    min_accuracy: 0.85
    require_min_neurons: 6
    size_weight: 0.0
    target_pruning_rate: 0.6
    validation_strategy: batch
training:
  batch_size: 32
  enabled: true
  epochs: 1000
  learning_rate: 0.001
  save_dir: models/original/sigmoid/creditcard
