dataset:
  data_path: data/heart.csv
  input_features: 13
  model_dir: models/heart
  model_path: models/original/tanh/heart
  name: heart
  num_classes: 5
  path: models/original/tanh/heart
  target_column: num
export:
  edge_impulse:
    enabled: false
    project_id: 669207
  enabled: true
  onnx_dir: models/{dataset_name}/{activation}/onnx
  save_dir: models/pruned/tanh/heart
inference:
  batch_size: 32
  enabled: true
  output_dir: results/inference/tanh/heart
model:
  activation: tanh
  base_dir: models/{dataset_name}/{activation}
  hidden_neurons: 26
  input_features: 13
  model_save_path: models/heart
output:
  results_dir: results/heart
  save_dir: models/pruned/tanh/heart
pruning:
  accuracy_drop: 0.05
  activity_threshold: 0.1
  correlation_threshold: 0.8
  enabled: true
  pruned: false
  save_dir: models/pruned/tanh/heart
  sensitivity_threshold: 0.01
  validation:
    accuracy_weight: 1.0
    batch_size: 3
    max_accuracy_drop: 0.05
    max_neurons_pruned: 8
    min_accuracy: 0.85
    require_min_neurons: 6
    size_weight: 0.0
    target_pruning_rate: 0.6
    validation_strategy: batch
training:
  batch_size: 32
  enabled: true
  epochs: 1000
  learning_rate: 0.001
  save_dir: models/original/tanh/heart
