dataset:
  data_path: data/breast_cancer.csv
  input_features: 30
  model_dir: models/breast_cancer
  model_path: models/original/sigmoid/breast_cancer
  name: breast_cancer
  num_classes: 2
  path: models/original/sigmoid/breast_cancer
  target_column: Diagnosis
export:
  edge_impulse:
    enabled: false
    project_id: 669207
  enable_onnx: true
  enabled: true
  onnx_dir: models/onnx
  original_model_dir: models/original
  pruned_model_dir: models/pruned
  save_dir: models/pruned/sigmoid/breast_cancer
inference:
  batch_size: 32
  enabled: true
  output_dir: results/inference/sigmoid/breast_cancer
model:
  activation: sigmoid
  base_dir: models/original/relu/breast_cancer
  hidden_neurons: 60
  input_features: 30
  model_save_path: models/breast_cancer
output:
  results_dir: results/breast_cancer
  save_dir: models/pruned/sigmoid/breast_cancer
pruning:
  accuracy_drop: 0.05
  activity_threshold: 0.1
  correlation_threshold: 0.8
  enabled: true
  pruned: false
  save_dir: models/pruned/sigmoid/breast_cancer
  sensitivity_threshold: 0.01
  validation:
    accuracy_weight: 1.0
    batch_size: 3
    max_accuracy_drop: 0.05
    max_neurons_pruned: 8
    min_accuracy: 0.85
    require_min_neurons: 3
    size_weight: 0.0
    target_pruning_rate: 0.6
    validation_strategy: batch
training:
  batch_size: 32
  enabled: true
  epochs: 1000
  learning_rate: 0.001
  save_dir: models/original/sigmoid/breast_cancer
