dataset:
  data_path: data/yeast.csv
  input_features: 8
  model_dir: models/yeast
  model_path: models/original/sigmoid/yeast
  name: yeast
  num_classes: 10
  path: models/original/sigmoid/yeast
  target_column: localization_site
export:
  edge_impulse:
    enabled: false
    project_id: 669207
  enabled: true
  onnx_dir: models/yeast/relu/onnx
  save_dir: models/pruned/sigmoid/yeast
inference:
  batch_size: 32
  enabled: true
  output_dir: results/inference/sigmoid/yeast
model:
  activation: sigmoid
  base_dir: models/yeast/relu
  hidden_neurons: 20
  input_features: 8
  model_save_path: models/yeast
output:
  results_dir: results/yeast
  save_dir: models/pruned/sigmoid/yeast
pruning:
  accuracy_drop: 0.05
  activity_threshold: 0.1
  correlation_threshold: 0.8
  enabled: true
  pruned: false
  save_dir: models/pruned/sigmoid/yeast
  sensitivity_threshold: 0.01
  validation:
    accuracy_weight: 1.0
    batch_size: 3
    max_accuracy_drop: 0.05
    max_neurons_pruned: 8
    min_accuracy: 0.85
    require_min_neurons: 6
    size_weight: 0.0
    target_pruning_rate: 0.6
    validation_strategy: batch
training:
  batch_size: 32
  enabled: true
  epochs: 1000
  learning_rate: 0.001
  save_dir: models/original/sigmoid/yeast
